version: "3"

services:
  # Nodejs Api Container
  email_service:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=docker_container
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - app_data:/usr/src/app/data/uploads
    depends_on:
      - mongodb
    restart: always

  # Nginx container
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - email_service
    ports:
      - 80:80
    restart: always

  # MongoDB Container
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
    restart: always

volumes:
  app_data:
  server_log:
  mongodb_data:
